pull_request_rules:
  - name: dismiss approvals on new commit
    conditions: [base=main]
    actions: { dismiss_reviews: { approved: true } }
  - name: merge on one approval
    conditions: ["#approved-reviews-by>=1", label=s2]
    actions: { merge: { method: merge } }
